[package]
name = "rust-wasm"
version = "0.1.0"
authors = ["Joao Henrique Serodio Ulbinski <joao.ulbinski@iesde.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.11.0"
